# Generated by Django 4.1.7 on 2023-02-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=12, null=True)),
                ('whp_nmbr', models.CharField(max_length=12, null=True)),
                ('reference_no', models.CharField(max_length=10, null=True)),
                ('seller', models.CharField(max_length=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categories')),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('product', 'booking_start_date', 'booking_end_date'), name='unique_booking'),
        ),
    ]
